name: quizzes_mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# app version
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies 
dependencies:
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^4.0.0
  file_picker: ^4.0.0
  flutter_local_notifications: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0
  flutter_svg: any
  get: ^4.1.4
  get_it: ^7.1.3
  google_maps_flutter: ^2.0.6
  heic_to_jpg: ^0.2.0
  image_picker: ^0.8.0+1
  intl: ^0.17.0
  logger: ^1.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  permission_handler: ^10.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.7
  path_provider: ^2.0.11
  dots_indicator: ^2.1.0
  carousel_slider: ^4.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package 
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dynamic_assets/images/
    - assets/static_assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
